### search functionality
GET http://127.0.0.1:3000/search-all
Content-Type: application/json

{
}

### check search warn functionality
GET http://127.0.0.1:3000/search
Content-Type: application/json

{
  "level" : "warn"
}

### check search with traceId functionality
GET http://127.0.0.1:3000/search
Content-Type: application/json

{
  "traceId" : "abc-xyz-123"
}

### check search error functionality
GET http://127.0.0.1:3000/search
Content-Type: application/json

{
  "level" : "error"
}


### check search regexp functionality (this does not work)
GET http://127.0.0.1:3000/search-reg
Content-Type: application/json

{
  "query": {
    "regexp": {
      "message": {
        "value": "Failed.*"
      }
    }
  }
}

### check search regexp with querystring functionality
GET http://127.0.0.1:3000/search-reg?q={"query_string": {"query": "Failed*","default_field": "message"}}

### check search regexp with querystring and timestamp functionality
GET http://127.0.0.1:3000/search-reg?q={"query_string": {"query": "[2023-09-15T00:00:00Z TO 2023-11-19T23:59:59Z]","default_field": "timestamp"}}


###Insert doc
POST http://127.0.0.1:3000/
Content-Type: application/json

{
	"level": "warn",
	"message": "Failed to connect to DB",
    "resourceId": "server-1234",
	"timestamp": "2023-09-15T08:00:00Z",
	"traceId": "abc-xyz-123",
    "spanId": "span-456",
    "commit": "5e5342f",
    "metadata": {
        "parentResourceId": "server-0987"
    }
}